# Generated by Django 5.2 on 2025-04-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_wechatloginstate_user_wechat_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='purpose',
            field=models.CharField(choices=[('register', '注册'), ('login', '登录'), ('reset_password', '重置密码'), ('bind_phone', '绑定手机号')], max_length=20, verbose_name='用途'),
        ),
    ]
